### ISSUE TITLE
updated this sample to latest version

### ISSUE THREAD

**Issue by vidya091209** [jsreport/jsreport-dotnet-example-docker#3]
i was trying with latest version there seems to be some issue.

**Comment by vidya091209** [comment]
i am getting this error Error rendering report: rendering has finished with errors:A critical error occurred while trying to execute the render command (2). Failed to launch chrome!/tmp/jsreport/compile/jsreport-2.9.0-BkIEYvyxv/chrome/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directoryTROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md (1). caused by error (2):-> stackError:    at onCriticalError (/snapshot/jsreport/node_modules/jsreport-cli/lib/commands/render.js:302:19)    at /snapshot/jsreport/node_modules/jsreport-cli/lib/commands/render.js:201:16    at processTicksAndRejections (internal/process/task_queues.js:97:5)caused by error (1):-> stackError: Failed to launch chrome!/tmp/jsreport/compile/jsreport-2.9.0-BkIEYvyxv/chrome/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directoryTROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md    at Client.render (/snapshot/jsreport/node_modules/jsreport-client/lib/client.js)    at processTicksAndRejections (internal/process/task_queues.js:97:5)    at async startRender (/snapshot/jsreport/node_modules/jsreport-cli/lib/commands/render.js:319:24)    at async /snapshot/jsreport/node_modules/jsreport-cli/lib/commands/render.js:186:24    at async Commander.executeCommand (/snapshot/jsreport/node_modules/jsreport-cli/lib/commander.js:242:22)Remote stack: Error: Failed to launch chrome!/tmp/jsreport/compile/jsreport-2.9.0-BkIEYvyxv/chrome/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directoryTROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md    at onClose (/snapshot/jsreport/node_modules/puppeteer/lib/Launcher.js:348:14)    at Interface.<anonymous> (/snapshot/jsreport/node_modules/puppeteer/lib/Launcher.js:337:50)    at Interface.emit (events.js:323:22)    at Interface.close (readline.js:409:8)    at Socket.onend (readline.js:187:10)    at Socket.emit (events.js:323:22)    at endReadableNT (_stream_readable.js:1204:12)    at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by pofider** [comment]
Its updated now, I apologize for the delay
```
# install chrome with deps, see https://github.com/jsreport/jsreport/blob/master/docker/full/Dockerfile
RUN apt-get update && apt-get install -y --no-install-recommends libgconf-2-4 gnupg git curl wget ca-certificates libgconf-2-4 && \
    wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && \
    sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' && \
    apt-get update && \  
    apt-get install -y lsb-release google-chrome-stable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst libxtst6 libxss1 --no-install-recommends

# debian needs this additional install
RUN apt-get install -y libx11-6 libx11-xcb1

ENV chrome_launchOptions_executablePath google-chrome-stable
ENV chrome_launchOptions_args --no-sandbox,--disable-dev-shm-usage,--single-process,--no-zygote
```
