### ISSUE TITLE
Doesn't work with .NET6 / mcr.microsoft.com/dotnet/aspnet:6.0-buster-slim missing

### ISSUE THREAD

**Issue by andrercarvalho** [jsreport/jsreport-dotnet-example-docker#5]
Do you have any sugestion to run in .Net6 ?
The last image available with debian is 6.0-bullseye-slim but this is in debian 11 and not debian 10.
With the image 6.0-bullseye-slim the build process gives error because some packages are unavailable in debian 11

EXAMPLE:
Package libappindicator3-1 is not available, but is referred to by another package.
#6 8.162 This may mean that the package is missing, has been obsoleted, or
#6 8.162 is only available from another source
#6 8.162 
#6 8.311 E: Package 'libappindicator3-1' has no installation candidate
#6 ERROR: executor failed running [/bin/sh -c apt-get update &&     apt-get install -y ca-certificates fonts-liberation libappindicator3-1 libasound2 libatk-bridge2.0-0 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 lsb-release wget xdg-utils]: exit code: 100

There is some workaround to this or i have to keep in .Net5 version?

Thanks in advance

**Comment by pofider** [comment]
This seems to works for me well.

```
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
RUN apt-get update

# install chrome with deps, see https://github.com/jsreport/jsreport/blob/master/docker/full/Dockerfile
RUN apt-get update && apt-get install -y --no-install-recommends libgconf-2-4 gnupg git curl wget ca-certificates libgconf-2-4 && \
    wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && \
    sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' && \
    apt-get update && \  
    apt-get install -y lsb-release google-chrome-stable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst libxtst6 libxss1 --no-install-recommends

# debian needs this additional install
RUN apt-get install -y libx11-6 libx11-xcb1

ENV chrome_launchOptions_executablePath google-chrome-stable
ENV chrome_launchOptions_args --no-sandbox,--disable-dev-shm-usage,--single-process,--no-zygote

WORKDIR /app
EXPOSE 80
```

**Comment by andrercarvalho** [comment]
Thanks for your reply @pofider
Yes i can confirm that your solution works well.
I realized that im using some extra linux packages in dockerfile so the error was related to that.
So if anyone needs to use the package "libappindicator3-1", the solution for debian 11 is to replace it by "libayatana-appindicator3-1"

Best Regards
