### ISSUE TITLE
Kubernetes resources

### ISSUE THREAD

**Issue by MoeHamdan** [jsreport/jsreport-dotnet-example-docker#6]
Hello 

Thanks for the example. 
I am hosting it using kubernetes, however I am not sure what is the proper configuration for resources (limit/request cpu/mem) also what is the minimum number of pod that should be available.

Thanks

**Comment by pofider** [comment]
You need to try it out, jsreport runs your code, therefore we can't give you any recommendation on what is the right limit.
200mb should be the minimum.

One pod is fine for start.
